### ISSUE TITLE
ssm is broken on Fedora 37 (LUKS-encrypted partition)

### ISSUE THREAD

**Issue by tesseract-rh** [system-storage-manager/ssm#14]
[root@showrunner ~]# cat /etc/fedora-release
Fedora release 37 (Thirty Seven)
[root@showrunner ~]# ssm
Traceback (most recent call last):
  File "/usr/bin/ssm", line 51, in <module>
    from ssmlib import main
  File "/usr/lib/python3.11/site-packages/ssmlib/main.py", line 31, in <module>
    from ssmlib.backends import lvm, crypt, btrfs, md, multipath
  File "/usr/lib/python3.11/site-packages/ssmlib/backends/crypt.py", line 60, in <module>
    CRYPTSETUP_VERSION = get_cryptsetup_version()
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ssmlib/backends/crypt.py", line 55, in get_cryptsetup_version
    version = list(map(int, output.strip().split()[-1].split('.', 3)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'PWQUALITY'
[root@showrunner ~]#

**Comment by lczerner** [comment]
Hi, thanks for the report. It seems that the version string has changed. SSM is no longer maintained really, but this seems to be easy enough to fix, so maybe I'll get around doing it. Although I can't promise anything, sorry.

**Comment by tesseract-rh** [comment]
Hey, no worries!
I've noticed the project has been kind of dead for a while now. It's a pity though. I really loved the tool. 
Anyway, thanks for the ping back. :-) Much appreciated.

**Comment by SupremeGit** [comment]
Incredible.
So, ssm is dead eh.
What was the problem with it, was it too useful?  Too easy to use? What?

In function get_cryptsetup_version():
~~~
        #older versions of cryptsetup give this:
        ## cryptsetup --version
        #cryptsetup 2.3.7

        #new versions give this
        ## cryptsetup --version
        #cryptsetup 2.6.0 flags: UDEV BLKID KEYRING FIPS KERNEL_CAPI PWQUALITY 

        #ssm did have this absurd code, to get the version:
        #version = list(map(int, output.strip().split()[-1].split('.', 3)))

        #just change it to something simple like this for christ's sake:
        version = output.strip().split(' ')[1]    #[0] is first substring, [1] is 2nd
~~~

**Comment by lczerner** [comment]
Hi John,volunteering for maintainership ? ;)But seriously, my employer didn’t have much interest in it and I haven’t had time to give it attention. It didn't help I haven't heard of anyone  actually using it.But the code is out there and open source. Feel free to resurrect it. You’re welcome 😉 -Lukas  V čt, čvn 1, 2023 v 03:37, John ***@***.***> napsal/a:  
Incredible.
So, ssm is dead eh.
What was the problem with it, was it too useful?  Too easy to use? What?
In function get_cryptsetup_version():
        #older versions of cryptsetup give this:
        ## cryptsetup --version
        #cryptsetup 2.3.7

        #new versions give this
        ## cryptsetup --version
        #cryptsetup 2.6.0 flags: UDEV BLKID KEYRING FIPS KERNEL_CAPI PWQUALITY

        #ssm did have this absurd code, to get the version:
        #version = list(map(int, output.strip().split()[-1].split('.', 3)))

        #just change it to something simple like this for christ's sake:
        version = output.strip().split(' ')[1]    #[0] is first substring, [1] is 2nd
