### ISSUE TITLE
ssm info crashes

### ISSUE THREAD

**Issue by jtulak** [system-storage-manager/ssm#6]
This should be a standalone issue and not just a thread in #5. 

SSM crashes with info command for a certain storage configuration:

>   File "/usr/bin/ssm", line 59, in <module>
>     sys.exit(main.main())
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 2863, in main
>     args.func(args)
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 1989, in info
>     source.pinfo()
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 1187, in pinfo
>     misc.ptable(node.get_printable_details())
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 767, in get_printable_details
>     return self._get_printable_details()
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 941, in _get_printable_details
>     pool = self.get_pool_node(self)
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 680, in get_pool_node
>     alias = node.children[0].get_alias()
> IndexError: list index out of range
> 

Storage layout and debug output
`lsblk --fs`

> NAME                FSTYPE      LABEL            UUID                                   MOUNTPOINT
> sda                                                                                     
> ├─sda1              vfat                         4C61-AFD2                              /boot
> ├─sda2                                                                                  
> ├─sda3              ntfs                         3288359088355397                       
> ├─sda4              LVM2_member                  PB5cKZ-Bj3B-ErqR-i8Ic-vmHh-1C2i-ocZDkc 
> │ ├─SSD--pool-root  btrfs                        673d4ca2-da0f-4f69-b4ea-92b053fa2894   /
> │ └─SSD--pool-speed xfs                          248d63fe-567f-4e8a-88c3-faf1b2d9d4a3   /SSD_Storage/sherlock
> ├─sda5              ntfs                         2E1E47D11E47912F                       
> ├─sda6              LVM2_member                  ktjucp-nhoe-W1Ct-VMc5-x9H5-BhfI-QomD8G 
> │ └─SSD--pool-root  btrfs                        673d4ca2-da0f-4f69-b4ea-92b053fa2894   /
> └─sda7              ntfs        Windows RE tools FE740E16740DD1F7                       
> sdb                                                                                     
> ├─sdb1              ntfs        DATA             06A09630A0962669                       
> ├─sdb2              ntfs        RECOVERY         48A698BEA698ADC6                       
> ├─sdb3              LVM2_member                  FYQ6ZF-hmkk-Ru0o-pg1r-6zco-TKVo-6jdWqn 
> │ └─HDD--pool-home  btrfs                        36babb36-09fb-49b2-85c8-0fe42da27418   /home
> ├─sdb4              LVM2_member                  l0MWQB-gBap-qdGl-bc5Q-VQup-DKOu-XCSeii 
> │ └─HDD--pool-var   xfs                          d90479c3-02b2-4ad9-b845-9c4e68f307a2   /var
> └─sdb5              swap                         e9df8f79-47c8-4926-980a-783010fab5f1   [SWAP]

when I modify line 680 it reports

> (set(['/dev/dm-1', '/dev/mapper/HDD--pool-home']), "{'pool_name': 'btrfs_HDD--pool-home', 'major': '254', 'hide': False, 'partitioned': 0, 'parent_name': '/dev/sdb3', 'vol_size': 104853504, 'dev_free': 48209428.48, 'dev_name': '/dev/dm-1', 'dev_used': '56644075.52', 'human_name': '/dev/mapper/HDD--pool-home', 'dev_size': 104853504, 'minor': '1'}")
> Traceback (most recent call last):
>   File "/usr/bin/ssm", line 59, in <module>
>     sys.exit(main.main())
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 2868, in main
>     args.func(args)
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 1994, in info
>     source.pinfo()
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 1192, in pinfo
>     misc.ptable(node.get_printable_details())
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 772, in get_printable_details
>     return self._get_printable_details()
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 947, in _get_printable_details
>     out.append(('type', self.volume_type_name(pool['type'])))
> TypeError: 'NoneType' object has no attribute '__getitem__'

_Originally posted by @Sherlock-Holo in https://github.com/system-storage-manager/ssm/issues/5#issuecomment-423914492_

**Comment by jtulak** [comment]
I sent the patches fixing this issue to the SSM mailing list and I will merge them after a two weeks review period.

https://sourceforge.net/p/storagemanager/mailman/storagemanager-devel/thread/20181121175057.64068-1-jtulak%40redhat.com/#msg36473720
